stages:
  - test
  - build

test:
  image: jitesoft/composer:latest
  stage: test
  script:
    - composer install
    - composer test

build:tag:
  image: docker:latest
  stage: build
  script:
    - TAGS=$(helper "${CI_REGISTRY_NAME}" "latest,${CI_COMMIT_REF_NAMR},${CI_COMMIT_TAG}")
    - docker buildx build --platform linux/amd64,linux/arm64 --progress plain --push ${TAGS}
  tags:
    - buildx
    - protected
  only:
    - tags
