stages:
  - test
  - build

include:
  - file: /php/auto.yml
    project: jitesoft/gitlab-ci-lib

build:tag:
  image: docker:latest
  stage: build
  script:
    - TAGS=$(helper "${CI_REGISTRY_NAME}" "latest,${CI_COMMIT_REF_NAMR},${CI_COMMIT_TAG}")
    - docker buildx build --platform linux/amd64,linux/arm64 --progress plain --push ${TAGS}
  tags:
    - buildx
    - protected
  only:
    - tags
